### ISSUE TITLE
useragent string

### ISSUE THREAD

**Issue by kingosticks** [Joniator/SpotifyRipper#1]
Hi,

What's the purpose of https://github.com/Joniator/SpotifyRipper/blob/master/SpotifyRipper/SpotifyDownloader.cs#L23 ?

**Comment by Joniator** [comment]
["User-Agent" for your application - max 255 characters long The User-Agent should be a relevant, customer facing identification of your application
](https://developer.spotify.com/docs/libspotify/12.1.51/structsp__session__config.html#a69d5b5aa58c901d7916bdea6e5b75c88)

Some kind of identifier for your app I think, havent found the real usage tho, you can replace it with everything you want AFAIK.

**Comment by kingosticks** [comment]
I was wondering why it was set to MopidyDev

**Comment by Joniator** [comment]
That code was copied from another started and not even remotely finished project of mine similiar to mopidy, hence the name

**Comment by kingosticks** [comment]
Ahh right. thanks
